function u = deriv4(v,vdot,v2dot,v3dot,v4dot)
% Support function used to define the control functions
%
% :param v: vector 
% :param vdot: time derivative of vector v  
% :param v2dot: second time derivative of vector v  
% :param v3dot: third time derivative of vector v  
% :param v4dot: fourth time derivative of vector v  

% :returns: time derivative of the output of deriv3

    norma = vecnorm(v);
    norma1d = (vdot'*v)/norma;
    norma2d = (norma*(vdot'*vdot+v'*v2dot)-norma1d*(v'*vdot))/norma^2;
    helpnum2 = norma2d*norma^2;
    norma3d = ((norma*(v3dot'*v+3*(v2dot'*vdot))-norma2d*(vdot'*v))*norma^2 -...
                helpnum2*2*norma*norma1d)/norma^4;  
         
    norma4d = -15/norma^7 * (v'*vdot)^4 + 18/norma^5 * (v'*vdot)^2 * (v'*v2dot + vdot'*vdot) + ...
    -3/norma^3 * (vdot'*vdot + v'*v2dot)^2 - 2/norma^3 * (v'*vdot) * (6*(vdot'*v2dot) + 2*(v'*v3dot)) + ...
    +1/norma * (3*(v2dot'*v2dot) + 4*vdot'*v3dot + v'*v4dot);
    
   
    u = (-norma^3*v*norma4d + norma^4*v4dot + (8*v*norma^2*norma1d -...
        4*norma^3*vdot)*norma3d - 4*norma^3*norma1d*v3dot + 6*norma^2*norma2d^2*v +...
        (-36*v*norma*norma1d^2 - 6*norma^3*v2dot + 24*norma^2*vdot*norma1d)*norma2d +...
        24*norma1d^4*v + 12*norma^2*norma1d^2*v2dot - 24*vdot*norma*norma1d^3)/norma^5;
        

%     recall deriv3:   u = (v3dot*norma^3 + v2dot*norma1d*norma^2 - 3*vdot*norma2d*norma^2 -...
%                           v*norma3d*norma^2 + 2*v*norma2d*norma1d*norma - 2*vdot*norma1d^2*norma +...
%                           2*v*norma1d^3)/norma^8;
           
%       u = (v4dot*norma^3 + 3*v3dot*norma1d*norma^2+v3dot*norma1d*norma^2 +...
%           v2dot*(norma2d*norma^2 + 2*norma1d^2*norma) - 3*v2dot*(norma2d*norma^2) -...
%           3*vdot*(norma3d*norma^2 + 2*norma2d*norma2d*norma) - vdot*norma3d*norma^2 -...
%           v*(norma4d*norma^2 + 2*norma3d*norma1d*norma) + 2*vdot*norma2d*norma1d*norma +...
%           2*v*(norma3d*norma1d*norma + norma2d*(norma2d*norma + norma1d^2)) -...
%           2*v2dot*norma1d^2*norma - 2*vdot*(2*norma2d*norma1d*norma + norma1d^3) +...
%           2*vdot*norma1d^3 + 6*v*norma2d*norma1d^2)/norma^16;
    
end
